name: Deploy

on:
    push:
      branches: [main]
    pull_request:
      branches:
        - main
       
jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Test
          run: |
            npm install
            npm run test-component

        - name: Deploy
          if: github.ref == 'refs/heads/main'
          env:
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl "$DEPLOY_URL"
    test:
    # Operating system to run job
      runs-on: ubuntu-latest

    # Steps in job
      steps:
      # Get code from repo
        - name: Checkout code
          uses: actions/checkout@v1
  
        - name: Use Node.js 21.x
          uses: actions/setup-node@v1
          with:
            node-version: 21.x
  
        # Install dependencies
        - name: 🧰 Install Deps
          run: npm install
  
        # Run build
        - name: Run Build
          run: npm run build
        
        # Start server
        - name: Start the server
          env:
            MONGODB_URI: mongodb+srv://dbUser:rootroot@googlebooks.7s2ke.mongodb.net/?retryWrites=true&w=majority&appName=GoogleBooks
          run: |
            npm run start &
            npx wait-on http://localhost:3001 
  
        # Run tests
        - name: Run Tests
          run: npm run test-component
    